name: pocketly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  get_it: ^8.2.0
  go_router: ^16.2.4
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lucide_icons_flutter: ^3.1.1
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope/Manrope-Regular.ttf
        - asset: fonts/Manrope/Manrope-Medium.ttf
        - asset: fonts/Manrope/Manrope-SemiBold.ttf
        - asset: fonts/Manrope/Manrope-Bold.ttf
        - asset: fonts/Manrope/Manrope-ExtraBold.ttf
        - asset: fonts/Manrope/Manrope-ExtraLight.ttf
        - asset: fonts/Manrope/Manrope-Light.ttf
    
    - family: Outfit
      fonts:
        - asset: fonts/Outfit/Outfit-Thin.ttf
        - asset: fonts/Outfit/Outfit-ExtraLight.ttf
        - asset: fonts/Outfit/Outfit-Light.ttf
        - asset: fonts/Outfit/Outfit-Regular.ttf
        - asset: fonts/Outfit/Outfit-Medium.ttf
        - asset: fonts/Outfit/Outfit-SemiBold.ttf
        - asset: fonts/Outfit/Outfit-Bold.ttf
        - asset: fonts/Outfit/Outfit-ExtraBold.ttf
        - asset: fonts/Outfit/Outfit-Black.ttf
    
    - family: PlusJakartaSans
      fonts:
        - asset: fonts/PlusJarkataSans/PlusJakartaSans-ExtraLight.ttf
        - asset: fonts/PlusJarkataSans/PlusJakartaSans-ExtraLightItalic.ttf
        - asset: fonts/PlusJarkataSans/PlusJakartaSans-Light.ttf
        - asset: fonts/PlusJarkataSans/PlusJakartaSans-LightItalic.ttf
        - asset: fonts/PlusJarkataSans/PlusJakartaSans-Regular.ttf
        - asset: fonts/PlusJarkataSans/PlusJakartaSans-Italic.ttf
        - asset: fonts/PlusJarkataSans/PlusJakartaSans-Medium.ttf
        - asset: fonts/PlusJarkataSans/PlusJakartaSans-MediumItalic.ttf
        - asset: fonts/PlusJarkataSans/PlusJakartaSans-SemiBold.ttf
        - asset: fonts/PlusJarkataSans/PlusJakartaSans-SemiBoldItalic.ttf
        - asset: fonts/PlusJarkataSans/PlusJakartaSans-Bold.ttf
        - asset: fonts/PlusJarkataSans/PlusJakartaSans-BoldItalic.ttf
        - asset: fonts/PlusJarkataSans/PlusJakartaSans-ExtraBold.ttf
        - asset: fonts/PlusJarkataSans/PlusJakartaSans-ExtraBoldItalic.ttf
    
    - family: Raleway
      fonts:
        - asset: fonts/Raleway/Raleway-Thin.ttf
        - asset: fonts/Raleway/Raleway-ThinItalic.ttf
        - asset: fonts/Raleway/Raleway-ExtraLight.ttf
        - asset: fonts/Raleway/Raleway-ExtraLightItalic.ttf
        - asset: fonts/Raleway/Raleway-Light.ttf
        - asset: fonts/Raleway/Raleway-LightItalic.ttf
        - asset: fonts/Raleway/Raleway-Regular.ttf
        - asset: fonts/Raleway/Raleway-Medium.ttf
        - asset: fonts/Raleway/Raleway-SemiBold.ttf
        - asset: fonts/Raleway/Raleway-Bold.ttf
        - asset: fonts/Raleway/Raleway-BoldItalic.ttf
        - asset: fonts/Raleway/Raleway-ExtraBold.ttf
        - asset: fonts/Raleway/Raleway-ExtraBoldItalic.ttf
        - asset: fonts/Raleway/Raleway-Black.ttf
        - asset: fonts/Raleway/Raleway-BlackItalic.ttf