name: pocketly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.1
  go_router: ^16.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-Medium.ttf
        - asset: assets/fonts/Manrope-SemiBold.ttf
        - asset: assets/fonts/Manrope-Bold.ttf
        - asset: assets/fonts/Manrope-ExtraBold.ttf
        - asset: assets/fonts/Manrope-ExtraLight.ttf
        - asset: assets/fonts/Manrope-Light.ttf