name: pocketly_api
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  drift: ^2.28.2
  sqlite3: ^2.9.2

dev_dependencies:
  build_runner: ^2.9.0
  dart_frog_lint: ^0.1.0
  drift_dev: ^2.28.3
  mocktail: ^1.0.3
  test: ^1.25.5
